name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: | 
           sudo apt-get update
           sudo apt-get install -y nasm libgmp-dev libflint-dev
    - name: make
      run: make
    - name: make test all
      run: make test_all
    - name: make openssl
      run: make test_openssl
